### ISSUE TITLE
SSo time out issue saml/sso

### ISSUE THREAD

**Issue by 321vka** [pateluday07/saml-sso-and-slo-demo-idp-azure-sp-springboot#2]
Hi Uday,
Thank you for sharing the knowledge and sharing the code. I followed the instruction and able to run your code properly. But inactivity of the 2-hour request redirect to "http://localhost:8080/saml/SSO" ANd on the backend, I am getting this error:

_authentication.CredentialsExpiredException: Authentication statement is too old to be used with value_ 

I had tried some other sample codes as well but facing the same issue every time.

Can you please guide me on how to fix this problem?. All I want to re-log in user after the session is time out. I will really appreciate any help I can get. Thank you in advance.

**Comment by pateluday07** [comment]
Hello @321vka,

Sorry for the late reply.

In order to help you with this issue, I have to simulate the same issue in my machine, unfortunately, I do not have an account on Azure AD as of today, so I won't be able to simulate the issue, hence I am not able to guide you here, sorry for that.
