### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by joeEulerity** [pateluday07/saml-sso-and-slo-demo-idp-azure-sp-springboot#4]
From a clean copy of the repo, I enter some dummy values in application.yaml, then run:

mvn clean package

There are numerous test failures with IllegalArgumentException, such as:

 Could not resolve placeholder 'service.provider.entity.id' in value "${service.provider.entity.id}"

I tried the following fixes:

1. copying src/main/resources to src/test/resources

2. adding the following clause to <build> in pom.xml
 		<testResources>
			<testResource>
				<directory>${project.basedir}/src/test/resources</directory>
				<filtering>true</filtering>
			</testResource>
			<testResource>
				<directory>${project.basedir}/src/main/resources</directory>
				<filtering>true</filtering>
			</testResource>
		</testResources>

but neither approach worked. Can you help?

**Comment by pateluday07** [comment]
Please skip the test cases when you package the application.
