### ISSUE TITLE
AADSTS50011: The reply URL is not valid

### ISSUE THREAD

**Issue by SaifKamaalAbulkhair** [pateluday07/saml-sso-and-slo-demo-idp-azure-sp-springboot#5]
Hey,

Where do I configure the reply URL in the application? As of now, we have configured the Reply URL as AD side and it works for localhost:8080 only. 

The moment we deploy the app on the server and change the reply URL to https://servername/appname i keep getting the below error

![image](https://user-images.githubusercontent.com/86179045/141122725-d0783139-49e5-49fe-bbac-276d818e2a28.png)

In my application.properties this is all that I have specified

#SSO
service.provider.entity.id=AppName
idp.metedata.url=https://login.microsoftonline.com/<id>/federationmetadata/2007-06/federationmetadata.xml?appid=d0f386-7e70-49c1-b4f7-XXXXXXXX
saml.keystore.password= password
saml.private.key.alias= alias
saml.private.key.password: password
saml.keystore.file=classpath:/saml/dev/samlKeystore.jks

Spring boot version is 2.5.5

Thnks

**Comment by pateluday07** [comment]
Well I developed, this demo some time ago so I don't remember it, and I don't have access to Azure as of today, so I won't be able to help you.

**Comment by biswajit576** [comment]
I am also getting same error.Could you help me on the above
