### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by bhagujava** [pateluday07/saml-sso-and-slo-demo-idp-azure-sp-springboot#6]
@pateluday07 

THank you for the sample but when login page opens and you submit valid credential not not even calling backend

**Comment by pateluday07** [comment]
Sorry for the late reply.

In my case it was working as expected, please check your configurations.

**Comment by bhagujava** [comment]
@pateluday07 Yeah its working as expected.

**Comment by bhagujava** [comment]
@pateluday07 how does idpDiscoReturnURL is generating ?  <form th:action="${idpDiscoReturnURL}" method="get">
